/**
 * API path constants grouped by domain — mirrors backend controller prefixes.
 */
export const API_ENDPOINTS = {
  ME: {
    PROFILE: "/v1/me",
    SESSION: "/v1/me/session",
    NAVIGATION: "/v1/me/navigation",
    MODULES: "/v1/me/modules",
    FEATURES: "/v1/me/features",
  },
  PLATFORM: {
    TENANTS: "/v1/platform/tenants",
    TENANT: (id: string) => `/v1/platform/tenants/${id}`,
    TENANT_SUBSCRIPTION: (id: string) => `/v1/platform/tenants/${id}/subscription`,
    TENANT_SUBSCRIPTION_CURRENT: "/v1/platform/tenant/subscription/current",
    TENANT_SUBSCRIPTION_BILLING: "/v1/platform/tenant/subscription/billing",
    TENANT_SUBSCRIPTION_ENTITLEMENTS: "/v1/platform/tenant/subscription/entitlements",
    TENANT_SUBSCRIPTION_USAGE: "/v1/platform/tenant/subscription/usage",
    TENANT_SUBSCRIPTION_AVAILABLE_PLANS: "/v1/platform/tenant/subscription/available-plans",
    TENANT_SUBSCRIPTION_CHANGE_PLAN: "/v1/platform/tenant/subscription/change-plan",
    SUBSCRIPTION: "/v1/platform/tenant/subscription",
    PROVISIONING: "/v1/platform/provisioning",
    PROVISIONING_STATUS: (tenantId: string) =>
      `/v1/platform/provisioning/tenants/${tenantId}/status`,
    PROVISIONING_RETRY: (tenantId: string) =>
      `/v1/platform/provisioning/tenants/${tenantId}/retry`,
  },
  SUBSCRIPTIONS: {
    BASE: "/v1/platform/subscriptions",
    TRIAL: "/v1/platform/subscriptions/trial",
    BY_ID: (id: string) => `/v1/platform/subscriptions/${id}`,
    BY_TENANT: (tenantId: string) => `/v1/platform/subscriptions/tenants/${tenantId}/current`,
    HISTORY: (id: string) => `/v1/platform/subscriptions/${id}/history`,
    ENTITLEMENTS: (id: string) => `/v1/platform/subscriptions/${id}/entitlements`,
    USAGE: (id: string) => `/v1/platform/subscriptions/${id}/usage`,
    ACTIVATE: (id: string) => `/v1/platform/subscriptions/${id}/activate`,
    RENEW: (id: string) => `/v1/platform/subscriptions/${id}/renew`,
    CANCEL: (id: string) => `/v1/platform/subscriptions/${id}/cancel`,
    CANCEL_AT_PERIOD_END: (id: string) => `/v1/platform/subscriptions/${id}/cancel-at-period-end`,
    SUSPEND: (id: string) => `/v1/platform/subscriptions/${id}/suspend`,
    RESUME: (id: string) => `/v1/platform/subscriptions/${id}/resume`,
    CHANGE_PLAN: (id: string) => `/v1/platform/subscriptions/${id}/change-plan`,
    RECALCULATE_ENTITLEMENTS: (id: string) => `/v1/platform/subscriptions/${id}/recalculate-entitlements`,
    ADDONS: (id: string) => `/v1/platform/subscriptions/${id}/addons`,
    ADDON: (id: string, addonId: string) => `/v1/platform/subscriptions/${id}/addons/${addonId}`,
  },
  SUPER_ADMIN: {
    DASHBOARD: "/v1/super-admin/dashboard",
    MODULE_REGISTRY: "/v1/super-admin/modules/registry",
    PLANS: "/v1/super-admin/plans",
    PLAN: (id: string) => `/v1/super-admin/plans/${id}`,
    PLAN_PUBLISH: (id: string) => `/v1/super-admin/plans/${id}/publish`,
    PLAN_DEPRECATE: (id: string) => `/v1/super-admin/plans/${id}/deprecate`,
    PLAN_ARCHIVE: (id: string) => `/v1/super-admin/plans/${id}/archive`,
    PLAN_VERSION: (id: string) => `/v1/super-admin/plans/${id}/versions`,
    PLAN_PRICES: (id: string) => `/v1/super-admin/plans/${id}/prices`,
    PLAN_LIMITS: (id: string) => `/v1/super-admin/plans/${id}/limits`,
    PLAN_MODULE_ENTITLEMENTS: (id: string) => `/v1/super-admin/plans/${id}/module-entitlements`,
    TENANTS: "/v1/super-admin/tenants",
    TENANT_SUBSCRIPTION_BILLING: (tenantId: string) =>
      `/v1/super-admin/tenants/${tenantId}/subscription/billing`,
    TENANT: (id: string) => `/v1/super-admin/tenants/${id}`,
    TENANT_SUMMARY: (id: string) => `/v1/super-admin/tenants/${id}/summary`,
    TENANT_360: (id: string) => `/v1/super-admin/tenants/${id}/360`,
    TENANT_STATUS: (id: string) => `/v1/super-admin/tenants/${id}/status`,
    TENANT_STATUS_HISTORY: (id: string) => `/v1/super-admin/tenants/${id}/status-history`,
    TENANT_MODULES: (tenantId: string) => `/v1/super-admin/tenants/${tenantId}/modules`,
    TENANT_MODULE_ENABLE: (tenantId: string, moduleCode: string) =>
      `/v1/super-admin/tenants/${tenantId}/modules/${moduleCode}/enable`,
    TENANT_MODULE_DISABLE: (tenantId: string, moduleCode: string) =>
      `/v1/super-admin/tenants/${tenantId}/modules/${moduleCode}/disable`,
    TENANT_MODULE_TRIAL: (tenantId: string, moduleCode: string) =>
      `/v1/super-admin/tenants/${tenantId}/modules/${moduleCode}/trial`,
    TENANT_MODULE_ENTITLEMENT_AUDIT: (tenantId: string) =>
      `/v1/super-admin/tenants/${tenantId}/modules/entitlement-audit`,
    TENANT_AUDIT: (tenantId: string) => `/v1/super-admin/audit/tenants/${tenantId}`,
    TENANT_PROVISIONING: (tenantId: string) =>
      `/v1/super-admin/tenants/${tenantId}/provisioning`,
    TENANT_PROVISIONING_RETRY: (tenantId: string) =>
      `/v1/super-admin/tenants/${tenantId}/provisioning/retry`,
    AUDIT: "/v1/super-admin/audit",
    AUDIT_TENANT: (tenantId: string) => `/v1/super-admin/audit/tenants/${tenantId}`,
  },
  ADMIN: {
    SETUP: "/v1/admin/tenant/setup",
    SETUP_STEP_COMPLETE: (step: string) => `/v1/admin/tenant/setup/steps/${step}/complete`,
    USERS: "/v1/admin/users",
    USER: (id: string) => `/v1/admin/users/${id}`,
    USER_ACCESS: (id: string) => `/v1/admin/users/${id}/access`,
    USER_DEACTIVATE: (id: string) => `/v1/admin/users/${id}/deactivate`,
    ROLES: "/v1/admin/roles",
    ROLE: (id: string) => `/v1/admin/roles/${id}`,
    ROLE_PERMISSIONS: (id: string) => `/v1/admin/roles/${id}/permissions`,
    PERMISSIONS: "/v1/admin/roles/permissions",
    ORGANIZATION_COMPANY: "/v1/admin/organization/company",
    ORGANIZATION_BRANCHES: "/v1/admin/organization/branches",
    ORGANIZATION_DEPARTMENTS: "/v1/admin/organization/departments",
  },
  MODULES: {
    EMPLOYEES: "/v1/employees",
    EMPLOYEE: (id: string) => `/v1/employees/${id}`,
    EXPENSES: "/v1/expenses",
    EXPENSE: (id: string) => `/v1/expenses/${id}`,
    EXPENSE_SUBMIT: (id: string) => `/v1/expenses/${id}/submit`,
    EXPENSE_APPROVE: (id: string) => `/v1/expenses/${id}/approve`,
    EXPENSE_REJECT: (id: string) => `/v1/expenses/${id}/reject`,
  },
  PUBLIC: {
    PLANS: "/v1/public/plans",
    PLANS_COMPARE: "/v1/public/plans/compare",
    PLAN_BY_CODE: (code: string) => `/v1/public/plans/${code}`,
  },
} as const;
